version: '3'

services:
  onomy:
    image: onomy/near-aurora-local:local
    restart: on-failure
    container_name: near-aurora-local
    volumes:
      - ./scripts:/scripts
    ports:
      - 3030:3030